### PR TITLE
Add Support for XCFrameworks

### PR DESCRIPTION
**Pull request by vikrem**
This builds on the work in #244, and addresses the review comment left in there:
- Only one of `-xc-frameworks` or `--platform` can be provided on the command line.
- Providing both causes an error.
- Providing neither goes ahead with the defaults of all platforms without xc framework support:

```
Usage: rome upload [FRAMEWORKS...] [--use-xcframeworks | --platform PLATFORMS] 
                   [--cache-prefix PREFIX] [--skip-local-cache] [--no-ignore] 
                   [--no-skip-current] [--concurrently]
  Uploads frameworks and dSYMs contained in the local Carthage/Build/<platform>
  to S3, according to the local Cartfile.resolved

Available options:
  -h,--help                Show this help text
  FRAMEWORKS...            Zero or more framework names. If zero, all frameworks
                           and dSYMs are uploaded.
  --use-xcframeworks       Search for .xcframeworks when performing the
                           operation.
  --platform PLATFORMS     Applicable platforms for the command. One of iOS,
                           MacOS, tvOS, watchOS, or a comma-separated list of
                           any of these values.
```

Combining them:

```
> rome upload --use-xcframeworks --platform iOS
Invalid option `--platform'
```

### CODE REVIEW

**Comment by tmspzz** [comment]
LGT 🥳 

But now... the __most__ painful part... 

Can we add integration tests to confirm this works? (apart from the fact that the CI stopped working. I will have to fix that)

**Comment by tmspzz** [comment]
> @tmspzz do you have an estimate on when you can get CI up and running again? Do we need CI running before we merge this? (i.e. can we just test locally?)

We don't need the CI to merge this. I am willing to accept a "it works on my machine".

I am trying to get it up again now but my experience with Github actions is limited, you can follow my attempts on `master`.

**Comment by ivanrein** [comment]
I'm getting this errors when using rome download with --use-xcframeworks 
Is it expected? 
image

**Comment by mpdifran** [comment]
@tmspzz when you have time feel free to double check my integration tests in [this PR](https://github.com/vikrem/Rome/pull/1)

**Comment by tmspzz** [comment]
Yep, skip bcsymbolmaps and dsyms. They are bundled in the xcframework

**Comment by Aranoledur** [comment]
Great work, guys. Maybe you can merge it as is for now and release "skip bcsymbolmaps and dsyms" later? Really waiting for this feature :/

**Comment by mpdifran** [comment]
What do you think @tmspzz? This is blocking us at Faire from using the new MacBooks.

**Comment by tmspzz** [comment]
@mpdifran alright but I will assign you the issue :)

**Comment by mpdifran** [comment]
@vikrem let's do it!

**Comment by mpdifran** [comment]
Actually it looks like you need to merge @tmspzz.

**Comment by tmspzz** [comment]
@vikrem @evandcoleman @mpdifran  Released as `v0.24.0.65` 🥳

**Pull request merged**
